### ISSUE TITLE
config in yaml in portal_resources

### ISSUE THREAD

**Issue by djay** [collective/collective.listingviews#30]
It would be better to have a configuration that can edited via the theme editor for more power users. The configuration registry feels like the wrong place given a listingview has to work hand in hand with diazo to make it look ok. This could be installed via c.themesitesetup.
However to install the display menu items it would need some kind of sync button in the control panel or theme editor similar to ambidexterity.

Format might be something like

```
views:
  - myiew:
       title: "My View"
       types:
         - News
      item_fields:
         - last_modified:tolocal
      listing_fields
         - id:tolink
fields:
   - myfield:
      title: My Field
      tal: context/myfield
      class: myfield
  
```
